server:
  port: 8888
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/  
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring:
  application:
    name: MyDiscoveryServiceService

