spring:
  application:
    name: cargoservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cargoservice
  cloud:
    config:
      enabled: false
server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    org:
      springframework:
        security: DEBUG
